In [8]:
import pandas as pd
df=pd.read_csv('shopeep_koreantop_clothing_shop_data.csv')

df = df[['join_month', 'join_day','join_year','shop_location','rating_bad','rating_good','rating_normal']]
print(df)
print('-'*80)

df['rating'] = df['rating_good'] * 2 + df['rating_normal'] - df['rating_bad'] * 3
print(df)
print('-'*80)

df['date'] = df['join_month'] + " " + df['join_day'].astype(str) + "," + df['join_year'].astype(str)
print(df)
print('-'*80)

df['new'] = df['join_year'] == 2021 
print(df)
print('-'*80)

import numpy as np
df['rate'] = np.where(df['rating_good'] >= 50000,'good','bad' )
print(df)
print('-'*80)

conditions = [(df['rating_good'] >= 30000) & (df['rating_bad'] <= 100),
              (df['rating_good'] >= 10000) & (df['rating_good'] < 30000) & (df['rating_bad'] <= 1000) & (df['rating_bad'] > 100),
              (df['rating_good'] < 10000)]
choices = ['blue', 'yellow','red']
df['flag'] = np.select(conditions, choices, default='black')
print(df)
print('-'*80)

    join_month  join_day  join_year               shop_location  rating_bad  \
0        April        27       2020                         NaN         181
1    September        25       2020    San Nicolas,Metro Manila          78
2    September        27       2016     Pasay City,Metro Manila        4647
3        April        30       2017        Binondo,Metro Manila          44
4      October        18       2016  Caloocan City,Metro Manila         680
..         ...       ...        ...                         ...         ...
741        May        22       2021          Legazpi City,Albay           0
742      March         3       2021                         NaN           1
743   December        20       2020                         NaN          16
744     August         2       2017        Binondo,Metro Manila        1960
745       June        17       2017     Pasay City,Metro Manila       13401

     rating_good  rating_normal
0          17510            729
1           2656            198
2        1071829          18073
3          18959            215
4          39252           2383
..           ...            ...
741           32              0
742            9              0
743          463             16
744       103289           3982
745       708666          30799

[746 rows x 7 columns]
--------------------------------------------------------------------------------
    join_month  join_day  join_year               shop_location  rating_bad  \
0        April        27       2020                         NaN         181
1    September        25       2020    San Nicolas,Metro Manila          78
2    September        27       2016     Pasay City,Metro Manila        4647
3        April        30       2017        Binondo,Metro Manila          44
4      October        18       2016  Caloocan City,Metro Manila         680
..         ...       ...        ...                         ...         ...
741        May        22       2021          Legazpi City,Albay           0
742      March         3       2021                         NaN           1
743   December        20       2020                         NaN          16
744     August         2       2017        Binondo,Metro Manila        1960
745       June        17       2017     Pasay City,Metro Manila       13401

     rating_good  rating_normal   rating
0          17510            729    35206
1           2656            198     5276
2        1071829          18073  2147790
3          18959            215    38001
4          39252           2383    78847
..           ...            ...      ...
741           32              0       64
742            9              0       15
743          463             16      894
744       103289           3982   204680
745       708666          30799  1407928

[746 rows x 8 columns]
--------------------------------------------------------------------------------
    join_month  join_day  join_year               shop_location  rating_bad  \
0        April        27       2020                         NaN         181
1    September        25       2020    San Nicolas,Metro Manila          78
2    September        27       2016     Pasay City,Metro Manila        4647
3        April        30       2017        Binondo,Metro Manila          44
4      October        18       2016  Caloocan City,Metro Manila         680
..         ...       ...        ...                         ...         ...
741        May        22       2021          Legazpi City,Albay           0
742      March         3       2021                         NaN           1
743   December        20       2020                         NaN          16
744     August         2       2017        Binondo,Metro Manila        1960
745       June        17       2017     Pasay City,Metro Manila       13401

     rating_good  rating_normal   rating               date
0          17510            729    35206      April 27,2020
1           2656            198     5276  September 25,2020
2        1071829          18073  2147790  September 27,2016
3          18959            215    38001      April 30,2017
4          39252           2383    78847    October 18,2016
..           ...            ...      ...                ...
741           32              0       64        May 22,2021
742            9              0       15       March 3,2021
743          463             16      894   December 20,2020
744       103289           3982   204680      August 2,2017
745       708666          30799  1407928       June 17,2017

[746 rows x 9 columns]
--------------------------------------------------------------------------------
    join_month  join_day  join_year               shop_location  rating_bad  \
0        April        27       2020                         NaN         181
1    September        25       2020    San Nicolas,Metro Manila          78
2    September        27       2016     Pasay City,Metro Manila        4647
3        April        30       2017        Binondo,Metro Manila          44
4      October        18       2016  Caloocan City,Metro Manila         680
..         ...       ...        ...                         ...         ...
741        May        22       2021          Legazpi City,Albay           0
742      March         3       2021                         NaN           1
743   December        20       2020                         NaN          16
744     August         2       2017        Binondo,Metro Manila        1960
745       June        17       2017     Pasay City,Metro Manila       13401

     rating_good  rating_normal   rating               date    new
0          17510            729    35206      April 27,2020  False
1           2656            198     5276  September 25,2020  False
2        1071829          18073  2147790  September 27,2016  False
3          18959            215    38001      April 30,2017  False
4          39252           2383    78847    October 18,2016  False
..           ...            ...      ...                ...    ...
741           32              0       64        May 22,2021   True
742            9              0       15       March 3,2021   True
743          463             16      894   December 20,2020  False
744       103289           3982   204680      August 2,2017  False
745       708666          30799  1407928       June 17,2017  False

[746 rows x 10 columns]
--------------------------------------------------------------------------------
    join_month  join_day  join_year               shop_location  rating_bad  \
0        April        27       2020                         NaN         181
1    September        25       2020    San Nicolas,Metro Manila          78
2    September        27       2016     Pasay City,Metro Manila        4647
3        April        30       2017        Binondo,Metro Manila          44
4      October        18       2016  Caloocan City,Metro Manila         680
..         ...       ...        ...                         ...         ...
741        May        22       2021          Legazpi City,Albay           0
742      March         3       2021                         NaN           1
743   December        20       2020                         NaN          16
744     August         2       2017        Binondo,Metro Manila        1960
745       June        17       2017     Pasay City,Metro Manila       13401

     rating_good  rating_normal   rating               date    new  rate
0          17510            729    35206      April 27,2020  False   bad
1           2656            198     5276  September 25,2020  False   bad
2        1071829          18073  2147790  September 27,2016  False  good
3          18959            215    38001      April 30,2017  False   bad
4          39252           2383    78847    October 18,2016  False   bad
..           ...            ...      ...                ...    ...   ...
741           32              0       64        May 22,2021   True   bad
742            9              0       15       March 3,2021   True   bad
743          463             16      894   December 20,2020  False   bad
744       103289           3982   204680      August 2,2017  False  good
745       708666          30799  1407928       June 17,2017  False  good

[746 rows x 11 columns]
--------------------------------------------------------------------------------
    join_month  join_day  join_year               shop_location  rating_bad  \
0        April        27       2020                         NaN         181
1    September        25       2020    San Nicolas,Metro Manila          78
2    September        27       2016     Pasay City,Metro Manila        4647
3        April        30       2017        Binondo,Metro Manila          44
4      October        18       2016  Caloocan City,Metro Manila         680
..         ...       ...        ...                         ...         ...
741        May        22       2021          Legazpi City,Albay           0
742      March         3       2021                         NaN           1
743   December        20       2020                         NaN          16
744     August         2       2017        Binondo,Metro Manila        1960
745       June        17       2017     Pasay City,Metro Manila       13401

     rating_good  rating_normal   rating               date    new  rate  \
0          17510            729    35206      April 27,2020  False   bad
1           2656            198     5276  September 25,2020  False   bad
2        1071829          18073  2147790  September 27,2016  False  good
3          18959            215    38001      April 30,2017  False   bad
4          39252           2383    78847    October 18,2016  False   bad
..           ...            ...      ...                ...    ...   ...
741           32              0       64        May 22,2021   True   bad
742            9              0       15       March 3,2021   True   bad
743          463             16      894   December 20,2020  False   bad
744       103289           3982   204680      August 2,2017  False  good
745       708666          30799  1407928       June 17,2017  False  good

       flag
0    yellow
1       red
2     black
3     black
4     black
..      ...
741     red
742     red
743     red
744   black
745   black

[746 rows x 12 columns]
--------------------------------------------------------------------------------

In [10]:
df = pd.read_csv("subset-covid-data.csv")

# cot moi: thang covid

# thap, tb, cao: 15%, 20-50 , >60 #(tao moi, chon cot, logic)

# b1: rate 
df["rate"] = df["cases"] / df["population"] * 100

logic1= df["rate"] <=15
logic2 = (df["rate"] >=20) & (df["rate"] <=50)
logic3 = df["rate"] >=60


df["thang covid"] = np.nan

df["thang covid"][logic1] = "thap"
df["thang covid"][logic2] = "tb"
df["thang covid"][logic3] = "cao"

print(df.head())

       country continent        date  day  month  year  cases  deaths  \
0  Afghanistan      Asia  2020-04-12   12      4  2020     34       3
1      Albania    Europe  2020-04-12   12      4  2020     17       0
2      Algeria    Africa  2020-04-12   12      4  2020     64      19
3      Andorra    Europe  2020-04-12   12      4  2020     21       2
4       Angola    Africa  2020-04-12   12      4  2020      0       0

  country_code  population      rate thang covid
0          AFG  37172386.0  0.000091        thap
1          ALB   2866376.0  0.000593        thap
2          DZA  42228429.0  0.000152        thap
3          AND     77006.0  0.027271        thap
4          AGO  30809762.0  0.000000        thap

C:\Users\congc\AppData\Local\Temp\ipykernel_3104\1267435265.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["thang covid"][logic1] = "thap"